### PR TITLE
Milestone/js

### PR DESCRIPTION
**Pull request by shepshook**
Hello! Here is the pull request with the JavaScript milestone. 

I've implemented a simple single-page application and divided main components of the app into several views with separate logics, so the page can be dynamically generated while corresponding data is loaded from Firebase Realtime DB.

Here is the [link](https://intensio0.web.app/) to deployed app. You can use test credentials to access the account with some pre-setup data:
_Email_: `email@test.test`
_Password_: `123456`

### CODE REVIEW

**Review by gmltA — COMMENTED** [review]
I can't reach https://intensio0.web.app/ ...

Update: I've managed to open start page, but can't go further.

**Comment by shepshook** [comment]
@gmltA May be we can have a call so you could show me what issues you have? Because I've just managed to log into using email@test.test account and perform all the main actions. Or any screenshots would be great too

**Comment by gmltA** [comment]
image

I'll try later.

**Comment by shepshook** [comment]
Wow, that was quite unexpected 😕. Okay, I've set up a new account with some test data, so you can try it out:
_Email_: `gmlta@email.com`
_Password_: `123456`

**Review by gmltA — APPROVED** [review]
That's a <kbd>9</kbd>.

So tell me what's left for the last milestone?

**Comment by shepshook** [comment]
@gmltA I consider that all the required functionality is implemented, so I was thinking about CI/CD configuration using GitHub Actions as the last milestone. Will that be enough for a decent mark or I should think more about providing some additional functionality?

**Comment by gmltA** [comment]
That'd be enough. Go for it!

**Pull request merged**
